//! AI-traffic classifier plugin.
//!
//! Detects LLM-generated SQL via syntactic heuristics + explicit hints
//! (User-Agent, application_name, session var). On a positive match,
//! tags the proxy's `QueryContext.attributes` with `ai_traffic=true`
//! so downstream plugins (token-budget, llm-guardrail) can gate.
//!
//! Heuristics — any of these flips the bit:
//! 1. `application_name` contains `gpt`, `claude`, `gemini`, `llm`,
//!    `chatbot`, `agent` (case-insensitive).
//! 2. SQL contains a JOIN across more than two tables that share no
//!    columns by name (proxy heuristic for "model invented this").
//! 3. SQL uses `SELECT *` against a known wide table.
//! 4. SQL contains generated-by markers like `/* generated by */`,
//!    `-- gpt-`, `-- generated`.
//! 5. Session variable `helios.ai_traffic` is `true` (explicit opt-in).
//!
//! All thresholds are configurable in `plugin.toml` once the plugin
//! runtime supports per-plugin config — today they're constants.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

const HINT_KEYWORDS: &[&str] = &[
    "gpt", "claude", "gemini", "llm", "chatbot", "agent", "openai", "anthropic",
];

const GENERATED_MARKERS: &[&str] = &[
    "/* generated", "-- generated", "-- gpt-", "/* by ai", "-- by claude",
];

/// Subset of the proxy's `QueryContext` we need. Wire format is JSON.
#[derive(Debug, Deserialize)]
struct CtxIn {
    query: String,
    #[serde(default)]
    hook_context: HookContextIn,
}

#[derive(Debug, Default, Deserialize)]
struct HookContextIn {
    #[serde(default)]
    attributes: std::collections::HashMap<String, String>,
}

/// Decision returned to the proxy. The runtime expects a `PreQueryResult`
/// — we always emit `Continue` and rely on the runtime to merge our
/// attribute write back into the live `HookContext` (TODO: needs proxy-
/// side support; until then, this plugin is a logging-only signal).
#[derive(Debug, Serialize)]
#[serde(rename_all = "PascalCase")]
enum Out {
    Continue,
}

#[no_mangle]
pub extern "C" fn pre_query(_ctx_ptr: i32, _ctx_len: i32) -> i64 {
    // Stub: real ABI lands when wasmtime integration in the proxy ships.
    // The shape of the dispatch is documented in the workspace README.
    0
}

/// Pure-function classifier — covered by unit tests so the heuristics
/// can evolve without re-running a full proxy.
fn classify(ctx: &CtxIn) -> bool {
    let q = ctx.query.to_lowercase();
    if let Some(app) = ctx.hook_context.attributes.get("application_name") {
        let lower = app.to_lowercase();
        if HINT_KEYWORDS.iter().any(|kw| lower.contains(kw)) {
            return true;
        }
    }
    if ctx
        .hook_context
        .attributes
        .get("helios.ai_traffic")
        .map(|s| s == "true")
        .unwrap_or(false)
    {
        return true;
    }
    if GENERATED_MARKERS.iter().any(|m| q.contains(m)) {
        return true;
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    fn ctx(query: &str, attrs: &[(&str, &str)]) -> CtxIn {
        let mut a = HashMap::new();
        for (k, v) in attrs {
            a.insert((*k).to_string(), (*v).to_string());
        }
        CtxIn {
            query: query.to_string(),
            hook_context: HookContextIn { attributes: a },
        }
    }

    #[test]
    fn detects_gpt_app_name() {
        assert!(classify(&ctx("SELECT 1", &[("application_name", "gpt-shopper")])));
    }

    #[test]
    fn detects_claude_app_name() {
        assert!(classify(&ctx("SELECT 1", &[("application_name", "ClaudeAgent")])));
    }

    #[test]
    fn detects_explicit_session_opt_in() {
        assert!(classify(&ctx("SELECT 1", &[("helios.ai_traffic", "true")])));
    }

    #[test]
    fn detects_generated_marker_in_sql() {
        assert!(classify(&ctx(
            "/* generated by GPT-4 */ SELECT * FROM users",
            &[]
        )));
    }

    #[test]
    fn ignores_human_traffic() {
        assert!(!classify(&ctx(
            "SELECT id FROM users WHERE id = 1",
            &[("application_name", "psql")]
        )));
    }
}
